#!/usr/bin/env bash
# vendor-wasm.sh — Copy the WASM decoder build output from npm packages into
# web/vendor/ so the PACS dashboard can load them from the served static tree
# with no bundler and no CDN dependency (design §4.5). Vendored files are
# committed to git, matching the precedent of committing web/mic-decoder.wasm.
#
# Only HTJ2K (OpenJPH) and JPEG-LS (CharLS) are vendored: the probe
# (scripts/probe-codecs.mjs) confirmed both decode 16-bit grayscale losslessly
# in-browser. JPEG-XL (@jsquash/jxl) is intentionally NOT vendored — its public
# decode() returns 8-bit RGBA ImageData, which cannot represent lossless 16-bit
# medical pixels, so JXL stays an informational (native-C reference) row.
#
# Run from web/:  npm install && bash scripts/vendor-wasm.sh
set -euo pipefail
cd "$(dirname "$0")/.."   # -> web/

NM=node_modules
VENDOR=vendor
mkdir -p "$VENDOR/openjph" "$VENDOR/charls"

copy() { echo "  $1 -> $2"; cp "$1" "$2"; }

echo "Vendoring HTJ2K (OpenJPH) ..."
copy "$NM/@cornerstonejs/codec-openjph/dist/openjphjs.js"   "$VENDOR/openjph/openjphjs.js"
copy "$NM/@cornerstonejs/codec-openjph/dist/openjphjs.wasm" "$VENDOR/openjph/openjphjs.wasm"

echo "Vendoring JPEG-LS (CharLS, decode-only wasm build) ..."
copy "$NM/@cornerstonejs/codec-charls/dist/charlswasm_decode.js"   "$VENDOR/charls/charlswasm_decode.js"
copy "$NM/@cornerstonejs/codec-charls/dist/charlswasm_decode.wasm" "$VENDOR/charls/charlswasm_decode.wasm"

pkgver() { node -p "require('./$NM/$1/package.json').version"; }
sha() { shasum -a 256 "$1" | awk '{print $1}'; }

cat > "$VENDOR/VERSIONS.md" <<EOF
# Vendored WASM decoders

Generated by \`scripts/vendor-wasm.sh\`. Do not edit by hand — re-run the script
after an \`npm install\` version bump. These files are committed to git.

| Codec | npm package | version | file | sha256 |
|-------|-------------|---------|------|--------|
| HTJ2K | @cornerstonejs/codec-openjph | $(pkgver @cornerstonejs/codec-openjph) | openjph/openjphjs.wasm | $(sha "$VENDOR/openjph/openjphjs.wasm") |
| JPEG-LS | @cornerstonejs/codec-charls | $(pkgver @cornerstonejs/codec-charls) | charls/charlswasm_decode.wasm | $(sha "$VENDOR/charls/charlswasm_decode.wasm") |

JPEG-XL (@jsquash/jxl $(pkgver @jsquash/jxl)) is deliberately NOT vendored:
its decode() returns 8-bit RGBA ImageData and cannot preserve lossless 16-bit
grayscale (see scripts/probe-codecs.mjs). JXL is shown as an informational
native-C reference row in the dashboard instead.
EOF

echo "Wrote $VENDOR/VERSIONS.md"
echo "Done."
